Repository WildCodeSchool/orleans-202109-php-project-valdespoir, pull requests merged in 2021-12, with the labels that each got.

#21 S1 us02
  assets/images/banner.jpg
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/variables.scss
  templates/home/index.html.twig
  templates/include/_banner.html.twig
Labels: reviewed

#29 S01-US01
  assets/images/logo2.png
  assets/styles/app.scss
  assets/styles/navbar.scss
  templates/base.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed

#32 change variable name and px
  assets/styles/app.scss
  assets/styles/variables.scss
Labels: reviewed, FIX

#33 commit dev to master
  assets/app.js
  assets/images/banner.jpg
  assets/images/logo2.png
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  composer.lock
  package.json
  symfony.lock
  templates/base.html.twig
  templates/home/index.html.twig
  templates/include/_banner.html.twig
  templates/include/_navbar.html.twig
  yarn.lock
Labels: reviewed

#34 fix navbar delete home icon
  templates/include/_navbar.html.twig
Labels: reviewed

#58 Fix banner
  assets/styles/banner.scss
  assets/styles/variables.scss
  templates/include/_banner.html.twig
Labels: reviewed, FIX

#60 NavBar Sticky-Top
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#30 Us04 sites page
  assets/images/placeholder-site.jpg
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/navbar.scss
  assets/styles/site.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20211217092423.php
  src/Controller/SiteController.php
  src/DataFixtures/SiteFixtures.php
  src/Entity/Site.php
  src/Repository/SiteRepository.php
  symfony.lock
  templates/site/index.html.twig
Labels: reviewed

#66 Footer Remove Images
  assets/images/footer_tondeuse.png
  assets/images/logo 3.png
  assets/images/logo3.svg
  assets/styles/_footer.scss
  assets/styles/app.scss
  assets/styles/variables.scss
  package-lock.json
  package.json
  templates/base.html.twig
  templates/include/_footer.html.twig
  yarn.lock
Labels: reviewed, correction done, FIX

#64 S01_US01_FIX02
  templates/include/_navbar.html.twig
Labels: reviewed

#70 détail-chantier
  assets/styles/app.scss
  composer.json
  composer.lock
  migrations/Version20211221171249.php
  src/Controller/SiteController.php
  src/DataFixtures/SiteFixtures.php
  src/Entity/Site.php
  templates/include/_navbar.html.twig
  templates/site/index.html.twig
  templates/site/show.html.twig
Labels: reviewed
