Repository WildCodeSchool/orleans-202109-php-project-valdespoir, pull requests merged in 2022-02, with the labels that each got.

#353 FIX edit image required false
  src/Form/ActualityType.php
  src/Form/PartnerType.php
  src/Form/SiteType.php
Labels: reviewed, FIX

#354 dev to master
  assets/images/iconValEspoir.png
  assets/images/logo3.png
  assets/styles/admin.scss
  assets/styles/banner.scss
  assets/styles/navbar.scss
  config/packages/translation.yaml
  migrations/Version20220126152421.php
  src/Controller/AdminJobOfferController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSiteController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/SiteFixtures.php
  src/Entity/Actuality.php
  src/Entity/JobOffer.php
  src/Entity/Site.php
  src/Form/ActualityType.php
  src/Form/ContactType.php
  src/Form/MemberType.php
  src/Form/PartnerType.php
  src/Form/SiteType.php
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/_form.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
  templates/admin_home/index.html.twig
  templates/admin_member/_delete_form.html.twig
  templates/admin_member/edit.html.twig
  templates/admin_partner/_form.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/include/_footer.html.twig
  templates/include/_navbar.html.twig
  templates/site/_banner.html.twig
Labels: reviewed

#356 change button
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#358 change description
  assets/styles/actualities.scss
  src/Form/ActualityType.php
Labels: reviewed, FIX

#359 add nl2br
  templates/member/index.html.twig
Labels: reviewed, FIX

#360 novalidate
  assets/styles/contact.scss
  src/Entity/Contact.php
  src/Form/ContactType.php
  templates/contact/newEmail.html.twig
Labels: reviewed, FIX

#379 fix routes english to franchais
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminJobOfferController.php
  src/Controller/AdminSiteController.php
  src/Controller/HomeController.php
  src/Controller/JobOfferController.php
  src/Controller/ResetPasswordController.php
  src/Controller/SiteController.php
Labels: reviewed, FIX

#380 fix partner ratio cover
  assets/styles/partner.scss
Labels: reviewed, FIX

#381 fix base.html.twig name
  templates/base.html.twig
Labels: reviewed, FIX

#382 fix-contact-form
  assets/styles/contact.scss
  templates/contact/index.html.twig
Labels: reviewed, FIX

#383 fix hover on card site
  assets/styles/job.scss
  assets/styles/site.scss
  templates/site/index.html.twig
Labels: reviewed, FIX

#384 Fix site
  assets/styles/site.scss
  src/Entity/Site.php
  templates/site/index.html.twig
  templates/site/show.html.twig
Labels: reviewed, FIX

#385 Fix job
  src/Entity/JobOffer.php
  src/Form/JobOfferType.php
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
Labels: reviewed, FIX

#386 add aucun partenaire
  templates/partner/index.html.twig
Labels: reviewed, FIX

#388 add legal notices from client datas ....
  templates/legal_notice/index.html.twig
Labels: reviewed, FIX

#389 fix-mediaquery et banner realisation
  assets/styles/app.scss
  assets/styles/banner.scss
  templates/site/_banner.html.twig
Labels: reviewed, review needed, FIX

#393 Fix carousel
  src/Controller/HomeController.php
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
Labels: reviewed, FIX

#394 fix entity partner
  src/Entity/Partner.php
Labels: reviewed, FIX

#395 customize errors 404 and 500
  symfony.lock
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: reviewed, correction done, FIX

#396 fix legal notice
  templates/legal_notice/index.html.twig
Labels: reviewed, FIX

#398 fix padding-banner-sites
  templates/site/_banner.html.twig
Labels: reviewed, FIX

#399 dev to master
  src/Controller/HomeController.php
  src/Entity/Partner.php
  symfony.lock
  templates/adminActuality/index.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminSite/index.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/legal_notice/index.html.twig
  templates/site/_banner.html.twig
Labels: reviewed, FIX

#397 change banner image
  assets/images/banner-job.jpeg
  assets/images/banner-job.jpg
  assets/images/banner-site.jpeg
  assets/images/banner-site.jpg
  assets/styles/banner.scss
Labels: reviewed, FIX

#401 Fix global
  assets/styles/banner.scss
  templates/home/_actualitiesCarousel.html.twig
  templates/site/_banner.html.twig
Labels: reviewed, FIX

#402 dev to master
  assets/images/banner-job.jpeg
  assets/images/banner-job.jpg
  assets/images/banner-site.jpeg
  assets/images/banner-site.jpg
  assets/styles/banner.scss
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/include/_adminNavbar.html.twig
  templates/include/_footer.html.twig
  templates/include/_navbar.html.twig
  templates/site/_banner.html.twig
Labels: reviewed
