Repository WildCodeSchool/orleans-202109-php-project-valdespoir, pull requests merged in 2022-01, with the labels that each got.

#26 S01 us08 sites carousel
  assets/images/placeholder-site.jpg
  assets/styles/app.scss
  assets/styles/carousel.scss
  assets/styles/home.scss
  assets/styles/variables.scss
  migrations/Version20211216093813.php
  public/index.php
  src/Controller/HomeController.php
  templates/base.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/home/index.html.twig
  templates/sites/index.html.twig
  webpack.config.js
Labels: reviewed

#72 dev to master
  assets/images/footer_tondeuse.png
  assets/images/logo 3.png
  assets/images/logo3.svg
  assets/images/placeholder-site.jpg
  assets/styles/_footer.scss
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/carousel.scss
  assets/styles/home.scss
  assets/styles/navbar.scss
  assets/styles/site.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  migrations/Version20211216093813.php
  migrations/Version20211221171249.php
  package-lock.json
  package.json
  public/index.php
  src/Controller/HomeController.php
  src/Controller/SiteController.php
  src/DataFixtures/SiteFixtures.php
  src/Entity/Site.php
  src/Repository/SiteRepository.php
  symfony.lock
  templates/base.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/home/index.html.twig
  templates/include/_banner.html.twig
  templates/include/_footer.html.twig
  templates/include/_navbar.html.twig
  templates/site/index.html.twig
  templates/site/show.html.twig
  templates/sites/index.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#73 fix migration
  migrations/Version20211221171249.php
  migrations/Version20220103164132.php
Labels: reviewed

#75 dev to master
  migrations/Version20211221171249.php
  migrations/Version20220103164132.php
Labels: reviewed

#76 S02 us01 contact form
  assets/styles/contact.scss
  config/packages/twig.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/.gitignore
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/contact/newEmail.html.twig
  webpack.config.js
Labels: reviewed

#84 S02_US10 Partner Banner
  src/Controller/PartnerController.php
  templates/partner/_banner.html.twig
  templates/partner/index.html.twig
Labels: reviewed

#89 change place of block banner
  templates/contact/index.html.twig
  templates/home/index.html.twig
  templates/partner/index.html.twig
  templates/site/index.html.twig
Labels: reviewed, FIX

#93 page-actualitys
  assets/styles/actualities.scss
  assets/styles/app.scss
  composer.json
  migrations/Version20220105113746.php
  src/Controller/ActualityController.php
  src/DataFixtures/ActualityFixtures.php
  src/Entity/Actuality.php
  src/Repository/ActualityRepository.php
  templates/actuality/index.html.twig
  templates/include/_navbar.html.twig
  yarn.lock
Labels: reviewed

#96 detail_activity
  src/Controller/ActualityController.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
Labels: reviewed

#98 S01 us07 job offers faker
  assets/images/placeholder.png
  composer.json
  composer.lock
  migrations/Version20211217090614.php
  src/Controller/JobOfferController.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/JobOffer.php
  src/Repository/JobOfferRepository.php
  templates/job_offer/index.html.twig
Labels: reviewed

#99 with migration
  migrations/Version20211217090614.php
  migrations/Version20220105113746.php
  migrations/Version20220106090212.php
  src/Controller/JobOfferController.php
Labels: reviewed, correction done

#101 FIX S01_US01 Navbar Routes
  src/Controller/PartnerController.php
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#102 fix-migrations
  migrations/Version20220106090212.php
  migrations/Version20220106120553.php
  yarn.lock
Labels: reviewed

#104 fix : add banner to job offers page
  templates/job_offer/_banner.html.twig
  templates/job_offer/index.html.twig
Labels: reviewed

#105 dev to master
  assets/images/placeholder.png
  assets/styles/actualities.scss
  assets/styles/app.scss
  assets/styles/contact.scss
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/services.yaml
  docker-entry.sh
  migrations/Version20220106120553.php
  src/Controller/ActualityController.php
  src/Controller/ContactController.php
  src/Controller/JobOfferController.php
  src/Controller/PartnerController.php
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/JobOfferFixtures.php
  src/Entity/Actuality.php
  src/Entity/Contact.php
  src/Entity/JobOffer.php
  src/Form/ContactType.php
  src/Repository/.gitignore
  src/Repository/ActualityRepository.php
  src/Repository/JobOfferRepository.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/contact/newEmail.html.twig
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
  templates/job_offer/_banner.html.twig
  templates/job_offer/index.html.twig
  templates/partner/_banner.html.twig
  templates/partner/index.html.twig
  templates/site/index.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#106 CAROUSEL_ACTIVITY
  src/Controller/ActualityController.php
  src/Controller/HomeController.php
  templates/actuality/index.html.twig
  templates/home/_actualitiesCarousel.html.twig
  templates/home/index.html.twig
Labels: reviewed, correction done

#129 FIX S01_US01 Navbar Logo spacing
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#130 NavBar Fix 3
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#131 Fix job offers width
  templates/job_offer/index.html.twig
Labels: reviewed, FIX

#132 add job offers carrousel on home page
  src/Controller/HomeController.php
  templates/home/_jobOfferCarousel.html.twig
  templates/home/index.html.twig
Labels: reviewed

#144 S03 us15 admin site index
  src/Controller/AdminSiteController.php
  src/Form/SiteType.php
  templates/adminSite/_delete_form.html.twig
  templates/adminSite/_form.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
Labels: reviewed

#147 CRUD-INDEX
  src/Controller/AdminActualityController.php
  src/Form/ActualityType.php
  templates/adminActuality/_delete_form.html.twig
  templates/adminActuality/_form.html.twig
  templates/adminActuality/edit.html.twig
  templates/adminActuality/index.html.twig
  templates/adminActuality/new.html.twig
Labels: reviewed

#148 S03 us16 admin site add
  src/Controller/AdminSiteController.php
  src/Entity/Site.php
  src/Form/SiteType.php
  templates/adminSite/_form.html.twig
  templates/adminSite/new.html.twig
  templates/base.html.twig
Labels: reviewed, correction done

#151 FIX add use assert
  src/Entity/Site.php
Labels: reviewed

#157 S03 us18 admin site delete
  src/Controller/AdminSiteController.php
  templates/adminSite/index.html.twig
Labels: reviewed

#158 ajout-actu
  src/Controller/AdminActualityController.php
  src/Entity/Actuality.php
  src/Form/ActualityType.php
  templates/adminActuality/_delete_form.html.twig
  templates/adminActuality/_form.html.twig
  templates/adminActuality/edit.html.twig
  templates/adminActuality/new.html.twig
Labels: reviewed

#161 EDIT-ACUALITY
  src/Controller/AdminActualityController.php
  templates/adminActuality/_delete_form.html.twig
  templates/adminActuality/edit.html.twig
Labels: reviewed

#165 S02_US02 Partner Page
  migrations/Version20220112132621.php
  src/Controller/PartnerController.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Partner.php
  src/Repository/PartnerRepository.php
  templates/partner/index.html.twig
Labels: reviewed

#167 add delete on job offers
  templates/adminJob_offer/_delete_form.html.twig
  templates/adminJob_offer/index.html.twig
Labels: reviewed

#170 delete table site
  migrations/Version20220112132621.php
Labels: reviewed, FIX

#171 S03_US12 Add partner
  src/Entity/Partner.php
  src/Form/PartnerType.php
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/new.html.twig
Labels: reviewed

#173 Dev To Master
  .gitignore
  composer.json
  composer.lock
  migrations/Version20220112132621.php
  phpmd.xml
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminJobOfferController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSiteController.php
  src/Controller/HomeController.php
  src/Controller/PartnerController.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Actuality.php
  src/Entity/JobOffer.php
  src/Entity/Partner.php
  src/Entity/Site.php
  src/Form/ActualityType.php
  src/Form/JobOfferType.php
  src/Form/PartnerType.php
  src/Form/SiteType.php
  src/Repository/PartnerRepository.php
  templates/actuality/index.html.twig
  templates/adminActuality/_delete_form.html.twig
  templates/adminActuality/_form.html.twig
  templates/adminActuality/edit.html.twig
  templates/adminActuality/index.html.twig
  templates/adminActuality/new.html.twig
  templates/adminJob_offer/_delete_form.html.twig
  templates/adminJob_offer/_form.html.twig
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/_delete_form.html.twig
  templates/adminSite/_form.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/base.html.twig
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/index.html.twig
  templates/include/_navbar.html.twig
  templates/job_offer/index.html.twig
  templates/partner/index.html.twig
  yarn.lock
Labels: reviewed

#154 fix and push
  migrations/Version20220112090930.php
  src/Controller/MemberController.php
  src/DataFixtures/MemberFixtures.php
  src/Entity/Member.php
  src/Repository/MemberRepository.php
  templates/member/index.html.twig
  yarn.lock
Labels: reviewed, correction done

#175 FIX Delete Button On Admin Partner
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/index.html.twig
Labels: reviewed, FIX

#176 FIX-MAJ-COULEUR-HOME
  assets/styles/app.scss
  assets/styles/banner.scss
  assets/styles/carousel.scss
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/include/_footer.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#178 FIX Partner Page Add Blank
  templates/partner/index.html.twig
Labels: reviewed, FIX

#179 add member route in navbar
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#181 FIX change name of the route
  src/Controller/ActualityController.php
  src/Controller/AdminActualityController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSiteController.php
  src/Controller/JobOfferController.php
  src/Controller/PartnerController.php
  src/Controller/SiteController.php
Labels: reviewed, FIX

#172 Us06 banner member
  templates/member/_banner.html.twig
  templates/member/index.html.twig
Labels: reviewed, FIX

#169 S03 us19 admin site upload
  assets/styles/site.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20220112141654.php
  src/DataFixtures/SiteFixtures.php
  src/DataFixtures/haie2.jpg
  src/Entity/Site.php
  src/Form/SiteType.php
  symfony.lock
  templates/site/index.html.twig
  templates/site/show.html.twig
  templates/sites/index.html.twig
Labels: reviewed, correction done

#185 Footer add grass
  templates/include/_footer.html.twig
Labels: reviewed, FIX

#182 css crud and add logo
  templates/adminActuality/_form.html.twig
  templates/adminActuality/edit.html.twig
  templates/adminActuality/index.html.twig
  templates/adminActuality/new.html.twig
  templates/adminJob_offer/_delete_form.html.twig
  templates/adminJob_offer/_form.html.twig
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/_form.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
  templates/admin_partner/_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
Labels: reviewed, FIX

#186 FIX Partner Page Card
  assets/styles/app.scss
  assets/styles/partner.scss
  templates/partner/index.html.twig
Labels: reviewed

#187 S03_US14 Delete Partner
  src/Controller/AdminPartnerController.php
Labels: reviewed

#189 Fix actualite
  assets/styles/actualities.scss
  assets/styles/variables.scss
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
Labels: reviewed

#190 Fix carousel
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
Labels: reviewed, FIX

#194 FIX-CARDS-SITES
  src/DataFixtures/SiteFixtures.php
  templates/actuality/show.html.twig
  templates/site/index.html.twig
  templates/site/show.html.twig
Labels: reviewed

#201 S03 us10 connexion admin
  config/packages/security.yaml
  config/routes.yaml
  migrations/Version20220113214101.php
  src/Controller/LoginController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  templates/include/_footer.html.twig
  templates/login/index.html.twig
  templates/security/login.html.twig
Labels: reviewed

#188 create crud adminMember set route and delete show
  src/Controller/AdminMemberController.php
  src/Form/MemberType.php
  templates/admin_member/_delete_form.html.twig
  templates/admin_member/_form.html.twig
  templates/admin_member/edit.html.twig
  templates/admin_member/index.html.twig
  templates/admin_member/new.html.twig
Labels: reviewed

#193 upload-actuality
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  migrations/Version20220114174716.php
  src/DataFixtures/ActualityFixtures.php
  src/Entity/Actuality.php
  src/Form/ActualityType.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/adminActuality/_delete_form.html.twig
Labels: reviewed

#204 Fix admin
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/site.scss
  templates/adminActuality/edit.html.twig
  templates/adminActuality/index.html.twig
  templates/adminActuality/new.html.twig
  templates/adminJob_offer/_delete_form.html.twig
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/_delete_form.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
  templates/admin_partner/_delete_form.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  webpack.config.js
Labels: reviewed, FIX

#207 FIX add column date
  migrations/Version20220117091202.php
  src/DataFixtures/SiteFixtures.php
  src/Entity/Site.php
  src/Form/SiteType.php
  templates/adminSite/_form.html.twig
  templates/adminSite/index.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/login/index.html.twig
Labels: reviewed

#209 S04 us04 admin footer
  assets/styles/_footer.scss
  assets/styles/app.scss
  templates/adminActuality/edit.html.twig
  templates/adminActuality/index.html.twig
  templates/adminActuality/new.html.twig
  templates/adminBase.html.twig
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/index.html.twig
  templates/adminSite/new.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/index.html.twig
  templates/admin_partner/new.html.twig
  templates/base.html.twig
  templates/include/_admin_footer.html.twig
Labels: reviewed

#213 Admin Navbar
  migrations/Version20220117125213.php
  templates/adminBase.html.twig
  templates/base.html.twig
  templates/include/_adminNavbar.html.twig
Labels: reviewed, correction done

#216 Fix footer
  assets/styles/_footer.scss
  templates/include/_footer.html.twig
Labels: reviewed

#217 FIX-ACTU-RESOLVE
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
Labels: reviewed, FIX

#224 S04 us06 select admin
  src/Controller/AdminSiteController.php
  templates/adminSite/index.html.twig
Labels: reviewed

#223 Fix joboffers cards
  config/packages/vich_uploader.yaml
  src/Controller/JobOfferController.php
  templates/home/_jobOfferCarousel.html.twig
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
Labels: reviewed, FIX

#214 page new
  migrations/Version20220112141654.php
  src/Controller/AdminMemberController.php
  src/Entity/Member.php
  templates/admin_member/new.html.twig
Labels: reviewed, correction done, FIX

#220 add pelouse in footer
  assets/images/pelouse.png
  templates/include/_footer.html.twig
Labels: reviewed, correction done, FIX

#230 FIX change button
  templates/adminActuality/_delete_form.html.twig
  templates/adminJob_offer/_delete_form.html.twig
  templates/adminSite/_delete_form.html.twig
  templates/admin_member/_delete_form.html.twig
  templates/admin_partner/_delete_form.html.twig
Labels: reviewed, FIX

#232 FIX delete migration
  migrations/Version20220117125213.php
Labels: reviewed, FIX

#231 page edit and flash message
  src/Controller/AdminMemberController.php
  templates/admin_member/edit.html.twig
Labels: reviewed

#234 Fix login
  assets/styles/login.scss
  assets/styles/site.scss
  templates/adminBase.html.twig
  templates/include/_admin_footer.html.twig
  templates/login/index.html.twig
  webpack.config.js
Labels: reviewed

#236 form selectes admin
  src/Controller/AdminActualityController.php
  templates/adminActuality/index.html.twig
Labels: reviewed

#237 add flash message for delete
  src/Controller/AdminMemberController.php
Labels: reviewed

#239 add routes
  templates/admin_member/index.html.twig
  templates/include/_adminNavbar.html.twig
Labels: reviewed, FIX

#240 fix admin member
  templates/admin_member/edit.html.twig
  templates/admin_member/index.html.twig
  templates/admin_member/new.html.twig
Labels: reviewed

#241 S04 us05 reset password
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  migrations/Version20220118210600.php
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/include/_footer.html.twig
  templates/login/index.html.twig
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
Labels: reviewed

#244 responcive carrousel
  assets/styles/actualities.scss
  assets/styles/carousel.scss
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
Labels: reviewed

#245 Admin home
  assets/styles/admin.scss
  config/packages/security.yaml
  src/Controller/AdminHomeController.php
  templates/adminJob_offer/index.html.twig
  templates/admin_home/index.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed

#247 fix carrousel actu
  templates/home/_actualitiesCarousel.html.twig
Labels: reviewed

#256 FIX change link
  templates/admin_home/index.html.twig
  templates/include/_adminNavbar.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#257 style member page
  assets/styles/member.scss
  templates/member/index.html.twig
Labels: reviewed

#253 Footer Pelouse
  templates/include/_footer.html.twig
Labels: reviewed, correction done, FIX

#252 Partner Page Upload Image
  src/Entity/Partner.php
  src/Form/PartnerType.php
  templates/partner/index.html.twig
Labels: reviewed, correction done

#258 fix admin member
  templates/admin_member/_form.html.twig
  templates/admin_member/index.html.twig
  templates/member/index.html.twig
Labels: reviewed, FIX

#259 fix-card-job
  assets/styles/app.scss
  assets/styles/job.scss
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
  templates/member/index.html.twig
Labels: reviewed

#261 Upload migration
  migrations/Version20220125113104.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/partner.jpeg
  templates/admin_partner/index.html.twig
  templates/include/_footer.html.twig
Labels: reviewed, FIX

#255 Fix banner
  assets/images/banner-actuality.jpg
  assets/images/banner-contact.jpg
  assets/images/banner-job.jpg
  assets/images/banner-member.png
  assets/images/banner-partner.jpg
  assets/images/banner-site.jpg
  assets/styles/banner.scss
  templates/actuality/_banner.html.twig
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/contact/_contact_banner.html.twig
  templates/contact/index.html.twig
  templates/include/_banner.html.twig
  templates/job_offer/_banner.html.twig
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
  templates/member/_banner.html.twig
  templates/member/index.html.twig
  templates/partner/_banner.html.twig
  templates/partner/index.html.twig
  templates/site/_banner.html.twig
  templates/site/index.html.twig
  templates/site/show.html.twig
Labels: reviewed, correction done, FIX

#262 fix-taille-pelouse
  assets/styles/_footer.scss
Labels: reviewed, FIX

#263 style button delete admin member
  templates/admin_member/_delete_form.html.twig
Labels: reviewed, FIX

#264 fix-card-partner
  assets/styles/partner.scss
  templates/partner/index.html.twig
Labels: reviewed

#265 resolve style cards
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
  templates/member/index.html.twig
Labels: reviewed

#266 delete h2
  templates/partner/index.html.twig
Labels: reviewed, FIX

#267 change color button
  templates/adminSite/_form.html.twig
Labels: reviewed, FIX

#269 size-image
  assets/styles/partner.scss
Labels: reviewed

#268 change page title for admin too
  templates/actuality/index.html.twig
  templates/adminActuality/index.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminSite/index.html.twig
  templates/admin_member/index.html.twig
  templates/admin_partner/index.html.twig
  templates/job_offer/index.html.twig
  templates/member/index.html.twig
  templates/partner/index.html.twig
  templates/site/index.html.twig
Labels: reviewed

#271 Fix navbar
  assets/styles/navbar.scss
  templates/base.html.twig
  templates/home/index.html.twig
  templates/include/_adminNavbar.html.twig
  templates/include/_navbar.html.twig
Labels: reviewed

#273 Category Partner
  migrations/Version20220126090731.php
  src/Controller/AdminPartnerController.php
  src/Controller/PartnerController.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Category.php
  src/Entity/Partner.php
  src/Repository/CategoryRepository.php
  templates/admin_partner/index.html.twig
  templates/category/index.html.twig
  templates/partner/index.html.twig
Labels: reviewed

#274 Fix navbar
  assets/styles/admin.scss
  assets/styles/navbar.scss
  templates/adminJob_offer/index.html.twig
  templates/admin_member/index.html.twig
  templates/admin_partner/index.html.twig
  templates/include/_adminNavbar.html.twig
Labels: reviewed, FIX

#275 change size of banner
  assets/styles/banner.scss
  assets/styles/variables.scss
Labels: reviewed, FIX

#276 select-partner
  assets/styles/partner.scss
  src/Form/CategoryType.php
  src/Form/PartnerType.php
  templates/adminJob_offer/index.html.twig
  templates/admin_member/index.html.twig
  templates/admin_partner/index.html.twig
  templates/partner/index.html.twig
Labels: reviewed

#277 Fix carousel
  templates/admin_member/index.html.twig
  templates/home/_actualitiesCarousel.html.twig
Labels: reviewed, FIX

#278 add legal-notice and suppr blank
  src/Controller/HomeController.php
  templates/include/_footer.html.twig
  templates/legal_notice/index.html.twig
Labels: reviewed

#279 change link
  templates/include/_adminNavbar.html.twig
Labels: reviewed, FIX

#280 change color
  assets/styles/navbar.scss
  templates/adminActuality/edit.html.twig
  templates/adminActuality/new.html.twig
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/new.html.twig
  templates/adminSite/edit.html.twig
  templates/adminSite/new.html.twig
  templates/admin_member/edit.html.twig
  templates/admin_member/new.html.twig
  templates/admin_partner/edit.html.twig
  templates/admin_partner/new.html.twig
Labels: reviewed, FIX

#281 fix-btn-edit
  templates/adminActuality/index.html.twig
  templates/adminJob_offer/index.html.twig
  templates/adminSite/index.html.twig
  templates/admin_home/index.html.twig
  templates/admin_member/index.html.twig
  templates/admin_partner/index.html.twig
Labels: reviewed, FIX

#282 change image
  assets/images/banner-actuality.jpg
  assets/images/banner-member.jpg
  assets/images/banner-member.png
  assets/styles/banner.scss
Labels: reviewed, FIX

#286 img pelouse
  assets/images/pelouse.png
  assets/images/pelouses.png
  templates/include/_footer.html.twig
Labels: reviewed

#313 fix-opacity-btn
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/contact/index.html.twig
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
  templates/partner/index.html.twig
  templates/site/show.html.twig
Labels: reviewed, FIX

#287 README
  README.md
Labels: reviewed, correction done

#319 migration for prod
  migrations/Version20220106120553.php
  migrations/Version20220112090930.php
  migrations/Version20220112132621.php
  migrations/Version20220114174716.php
  migrations/Version20220118090432.php
  migrations/Version20220118124149.php
  migrations/Version20220118145821.php
  migrations/Version20220118210600.php
  migrations/Version20220124143019.php
  migrations/Version20220125113104.php
  migrations/Version20220126090731.php
  migrations/Version20220126152421.php
  migrations/Version20220126153045.php
Labels: reviewed, DONE

#320 add marker in footer map
  templates/include/_footer.html.twig
Labels: reviewed, FIX

#322 taille h1
  assets/styles/app.scss
  assets/styles/variables.scss
  templates/site/show.html.twig
Labels: reviewed, FIX

#323 fix-hover_card
  assets/styles/actualities.scss
  assets/styles/job.scss
  assets/styles/partner.scss
  assets/styles/site.scss
Labels: reviewed, FIX, DONE

#324 FIX add home and change places in navbar
  assets/styles/admin.scss
  templates/include/_adminNavbar.html.twig
Labels: reviewed, FIX

#327 fix-H1-navbar
  assets/styles/actualities.scss
  assets/styles/job.scss
  assets/styles/site.scss
  templates/actuality/show.html.twig
  templates/site/show.html.twig
Labels: reviewed, FIX

#328 DEV TO MASTER
  README.md
  assets/images/pelouse.png
  assets/images/pelouses.png
  assets/styles/actualities.scss
  assets/styles/admin.scss
  assets/styles/app.scss
  assets/styles/job.scss
  assets/styles/partner.scss
  assets/styles/site.scss
  assets/styles/variables.scss
  migrations/Version20220106120553.php
  migrations/Version20220112090930.php
  migrations/Version20220112132621.php
  migrations/Version20220114174716.php
  migrations/Version20220118090432.php
  migrations/Version20220118124149.php
  migrations/Version20220118145821.php
  migrations/Version20220118210600.php
  migrations/Version20220124143019.php
  migrations/Version20220125113104.php
  migrations/Version20220126090731.php
  migrations/Version20220126152421.php
  migrations/Version20220126153045.php
  templates/actuality/index.html.twig
  templates/actuality/show.html.twig
  templates/adminActuality/new.html.twig
  templates/adminSite/new.html.twig
  templates/admin_home/index.html.twig
  templates/contact/index.html.twig
  templates/home/_actualitiesCarousel.html.twig
  templates/home/_jobOfferCarousel.html.twig
  templates/home/_sitesCarousel.html.twig
  templates/home/index.html.twig
  templates/include/_adminNavbar.html.twig
  templates/include/_footer.html.twig
  templates/job_offer/index.html.twig
  templates/job_offer/show.html.twig
  templates/partner/index.html.twig
  templates/site/show.html.twig
Labels: reviewed

#326 FIX add mail in to footer
  templates/include/_footer.html.twig
Labels: reviewed, FIX, DONE

#329 FIX color form site
  templates/adminSite/_form.html.twig
  templates/admin_partner/_form.html.twig
Labels: reviewed, FIX

#330 FIX Map
  templates/include/_footer.html.twig
Labels: reviewed, FIX

#325 Fix icon
  assets/images/iconValEspoir.png
  assets/images/logo3.png
  templates/base.html.twig
Labels: reviewed, correction done, FIX

#334 modif file fixture
  src/DataFixtures/ActualityFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/SiteFixtures.php
Labels: reviewed, FIX

#339 FIX add message flash
  src/Controller/AdminJobOfferController.php
  src/Controller/AdminMemberController.php
  src/Controller/AdminPartnerController.php
  src/Controller/AdminSiteController.php
Labels: reviewed, FIX

#341 FIX change logo
  templates/admin_home/index.html.twig
Labels: reviewed, FIX

#343 Fix form
  config/packages/translation.yaml
  templates/contact/index.html.twig
Labels: reviewed, FIX

#337 selected job
  src/Entity/JobOffer.php
Labels: reviewed, correction done, FIX

#338 selected actu
  src/Entity/Actuality.php
Labels: reviewed, correction done, FIX

#345 made a list with kinds of works
  assets/styles/banner.scss
  templates/site/_banner.html.twig
Labels: reviewed

#347 correction lastname firstname in contactType
  src/Form/ContactType.php
  templates/contact/index.html.twig
Labels: reviewed, FIX

#348 FIX change opacity
  assets/styles/navbar.scss
  templates/include/_navbar.html.twig
Labels: reviewed, FIX

#351 fix JobOffer admin
  src/Controller/AdminJobOfferController.php
  templates/adminJob_offer/edit.html.twig
  templates/adminJob_offer/new.html.twig
Labels: reviewed, FIX

#352 FIX resolve footer
  templates/base.html.twig
  templates/include/_footer.html.twig
Labels: reviewed, FIX
